export const ADMIN_ROUTE='/admin';
export const LOGIN_ROUTE='/login';
export const REGISTRATION_ROUTE='/registry';
export const ACCOUNT_ROUTE='/account';
export const COURSE_ROUTE='/course';
export const GUIDE_ROUTE='/';
export const GUIDEBOOK_ROUTE='/guidebook';
export const SANDBOX_ROUTE='/sandbox';
export const TRAINER_ROUTE='/trainer';
export const COURSEPAGE_ROUTE ='/coursepage'
export const COURSECARD_ROUTE='./coursecard'
export const FUNC_ROUTE = '/func'
export const BOOKMODULE_ROUTE = '/bookmodule'
export const BOOKARTICLE_ROUTE = '/bookarticle'